Update consuming-existing-aws-infrastructure.md to provide context to where networkSpec belongs
kubernetes-sigs/cluster-api-provider-aws pull request #2103
Opened 2020-11-10 20:16 UTC by cdenneen

Provide context as to where the `networkSpec` is to be updated inside the `kind: AWSManagedControlPlane`

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

2020-11-11 08:39 UTC, richardcase requested changes

2020-11-11 08:39 UTC, richardcase commented on docs/book/src/topics/consuming-existing-aws-infrastructure.md
> +apiVersion: controlplane.cluster.x-k8s.io/v1alpha3
For EKS based clusters it lives on **AWSManagedControlPlane** but for EC2 based clusters it lives on **AWSCluster**. For each of these kinds it is in the spec.

So i think we should we should either:
1. Change this part `Specifying existing infrastructure for Cluster API to use takes place in the specification for the AWSCluster object`
2. Have a separate example or section for each cluster type

2020-11-11 15:55 UTC, cdenneen commented
I signed it

2020-11-11 16:04 UTC, cdenneen commented
I signed it

2020-11-17 11:17 UTC, randomvariable commented
/ok-to-test

2020-11-19 07:26 UTC, richardcase approved these changes
/lgtm

2020-12-02 13:52 UTC, randomvariable commented
/approve

2020-12-02 14:02 UTC, merged