:seedling:, add Interruptible field to AWSMachine status
kubernetes-sigs/cluster-api-provider-aws pull request #2120
Opened 2020-11-22 16:37 UTC by akash-gautam

set Interruptible as true when SpotMarketOptions for AWSMachine is non-nil
fixes issue 1899

Signed-off-by: akash-gautam <gautamakash04@gmail.com>

**Which issue(s) this PR fixes** *
Fixes #1899

2020-11-22 18:10 UTC, akash-gautam commented
verify CLA again.

2020-11-30 10:54 UTC, richardcase requested changes

2020-11-30 10:54 UTC, richardcase commented on pkg/cloud/scope/machine.go
> +	if m.AWSMachine.Spec.SpotMarketOptions != (&infrav1.SpotMarketOptions{}) {
If `m.AWSMachine.Spec.SpotMarketOptions` is nil then interuptible will still be set which based on the comments in the issue would be wrong.

2020-11-30 10:54 UTC, richardcase commented
/ok-to-test

2020-11-30 11:22 UTC, richardcase commented
@akash-gautam - thanks for the PR 👍  As you have made some changes to the CRDs you will need to run `make generate`. Also its looks like there may be a linting failure, you can run the linter locally using `make lint`

2020-11-30 12:48 UTC, akash-gautam commented
@richardcase Thanks a lot for reviewing the PR and providing feedback. I worked on your suggestion but still, two checks are failing for me.

2020-11-30 12:53 UTC, richardcase commented
@akash-gautam  - i'll have a quick look

2020-11-30 13:24 UTC, richardcase commented
The "fuzzy" test are failing on the new field in the status. The fuzzy tests convert v1alpha2<->v1alpha3 and with the new field in the machine status you'll have "restore" the field value when it round trips and converts from v1alpha2->v1alpha3. If you are on the Kubernetes slack we can chat further there as it may be easier.

2020-11-30 16:57 UTC, richardcase commented
/lgtm

2020-11-30 16:58 UTC, richardcase commented
Thanks @akash-gautam for this change.

2020-12-02 13:58 UTC, randomvariable commented
/approve

2020-12-02 14:12 UTC, merged