bug: add namespace access to eks-contoller rules
kubernetes-sigs/cluster-api-provider-aws pull request #2514
Opened 2021-06-16 10:10 UTC by paulcarlton-ww

Add support for allowing access to private API endpoint from the
bastion host and also from specified security groups.

Fixes issue #2465

Signed-off-by: paulcarlton-ww <paul.carlton@weave.works>

**What type of PR is this?**

**What this PR does / why we need it**:

Without this feature the management cluster cannot access the API of a tenant cluster with only a private endpoint. Tenant cluster API access is required to complete provisioning.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2465

**Special notes for your reviewer**:
Untested, need to revisit this and add unit tests but need to prioritize other work right now 

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
Adds new fields to the `AWSManagedControlPlane` `endpointAccess` element to allow access to a private API endpoint 

endpointAccess:
    public: false
    private: true
    bastionAccess: true
    additionalSecurityGroups:
    - "..."
```
Note that the use of `additionalSecurityGroups` to add security groups that allow management cluster access to the tenant's private API may require the creation of a VPC peering connection, see #2484

2021-06-16 10:11 UTC, randomvariable commented
/ok-to-test

2021-06-16 11:37 UTC, randomvariable commented
Need to run 

```
make generate
```

You also will need to add v1alpha3 conversion using the annotation marshalling/unmarshalling.

2021-06-17 11:18 UTC, richardcase commented
@paulcarlton-ww - ping me on slack if you want a hand with the conversion part

2021-06-17 11:22 UTC, richardcase requested changes

2021-06-17 11:22 UTC, richardcase commented on controlplane/eks/api/v1alpha4/awsmanagedcontrolplane_types.go
> +	AdditionalSecurityGroups []*string `json:"additionalSecurityGroups,omitempty"`
We are moving away from a slice of pointers to structs due to an issue with conversion-gen (see #2495). Could you change to `[]string` and then check for the length of this elsewhere.

2021-06-17 14:19 UTC, paulcarlton-ww commented
> @paulcarlton-ww - ping me on slack if you want a hand with the conversion part

Will do, thanks @richardcase
Busy with other stuff right now will get back to this as soon as able

2021-06-26 18:22 UTC, shivi28 commented on pkg/cloud/services/eks/cluster.go
> +		sgID := securityGroups[infrav1.SecurityGroupBastion].ID
Handle nil pointer exception
```
if  securityGroup, okay := securityGroups[infrav1.SecurityGroupBastion]; okay{
  endpointAccess.AdditionalSecurityGroups = append(endpointAccess.AdditionalSecurityGroups, &securityGroup.ID)
}
```

2021-09-07 18:57 UTC, paulcarlton-ww commented
/retest-required

2021-09-09 15:19 UTC, paulcarlton-ww commented
Superseded by #2749

2021-09-09 15:19 UTC, closed without merging