Adding optional IAM policy creation for EKS Console
kubernetes-sigs/cluster-api-provider-aws pull request #2622
Opened 2021-07-29 11:06 UTC by Madhur97

**What type of PR is this?**
/kind feature

**What this PR does / why we need it**:
Adding an option to create a new IAM policy with the required permissions to view nodes/workloads using the EKS console so that this policy can be assigned to users/groups as mentioned [here](https://cluster-api-aws.sigs.k8s.io/topics/eks/eks-console.html)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2189 

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note

```

2021-07-29 11:19 UTC, shivi28 commented
/ok-to-test

2021-07-29 19:52 UTC, sedefsavas commented on cmd/clusterawsadm/api/bootstrap/v1alpha1/types.go
> +	EnableEKSViewNodesAndWorkloadsPolicy bool `json:"enableEKSViewNodesAndWorkloadsPolicy"`
Too long?
```suggestion
	EnableNodesAndWorkloadsPolicy bool `json:"enableEKSViewNodesAndWorkloadsPolicy"`
```

Also is this omitempty?

2021-07-30 04:20 UTC, Madhur97 commented on cmd/clusterawsadm/api/bootstrap/v1alpha1/types.go
> +	EnableEKSViewNodesAndWorkloadsPolicy bool `json:"enableEKSViewNodesAndWorkloadsPolicy"`
Updated the name and added omitempty

2021-07-30 08:06 UTC, sedefsavas commented
/lgtm

2021-07-30 08:17 UTC, richardcase requested changes

2021-07-30 08:17 UTC, richardcase commented on cmd/clusterawsadm/cloudformation/bootstrap/template.go
> +			ManagedPolicyName: t.NewManagedName("eks-view-nodes-workloads"),
I think we should shorten the name of this as its going to have a suffix appended and optionally a prefix which will make it long.

Perhaps something like `eks-console`?

2021-09-20 19:44 UTC, sedefsavas commented
@Madhur97 
what is the status on this PR?

2021-09-24 09:45 UTC, Madhur97 commented
Need to close this PR due to some issues. Opened a new [PR](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2790) .

2021-09-24 09:45 UTC, closed without merging