ROSA: External OIDC docs
kubernetes-sigs/cluster-api-provider-aws pull request #4940
Opened 2024-04-19 10:08 UTC by muraee

**What type of PR is this?**

/kind bug
/kind documentation

**What this PR does / why we need it**:
- Add docs for ROSA External OIDC feature
- Add missing required permissions to read/list configMaps.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4931

**Special notes for your reviewer**:

**Checklist**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] includes [emojis](https://github.com/kubernetes-sigs/kubebuilder-release-tools?tab=readme-ov-file#kubebuilder-project-versioning)
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
NONE
```

2024-04-19 10:11 UTC, muraee commented
cc @vincepri @nrb

2024-04-19 13:06 UTC, typeid requested changes
Thanks for adding this @muraee :) Suggested some fixes on typos.

2024-04-19 13:06 UTC, typeid commented on docs/book/src/topics/rosa/external-auth.md
> +When `enableExternalAuthProviders` is set to `true`, ROSA provider will generate a temporarily admin kubeconfig secert in the same namespace named `<cluster-name>-bootstrap-kubeconfig`. This kubeonco
```suggestion
When `enableExternalAuthProviders` is set to `true`, ROSA provider will generate a temporary admin kubeconfig secret in the same namespace named `<cluster-name>-bootstrap-kubeconfig`. This kubeconfig can be used to access the cluster to setup RBAC for OIDC users/groups.
```

2024-04-19 13:06 UTC, typeid commented on docs/book/src/topics/rosa/external-auth.md
> +For example, bind the `cluster-admin` to an oidc group, to give admin permissions to all users part of that group:
```suggestion
The following example binds the `cluster-admin` role to an OIDC group, giving all users in that group admin permissions.
```

2024-04-19 13:06 UTC, typeid commented on docs/book/src/topics/rosa/external-auth.md
> +1. Setup a new client in your OIDC provider with the following Redirect URL `<console-url>/auth/callback`. You can find the console URL in the status field of the `ROSAControlPlane` once the cluster
```suggestion
1. Setup a new client in your OIDC provider with the following Redirect URL: `<console-url>/auth/callback`. You can find the console URL in the status field of the `ROSAControlPlane` once the cluster is ready:
```

2024-04-19 13:06 UTC, typeid commented on docs/book/src/topics/rosa/external-auth.md
> +          issuerURL: https://login.microsoftonline.com/<tenant-id>/v2.0 # e.g. if using Micorsoft Entra ID
```suggestion
          issuerURL: https://login.microsoftonline.com/<tenant-id>/v2.0 # e.g. if using Microsoft Entra ID
```

2024-04-19 13:31 UTC, damdo commented
@muraee could you update the title to the bug emoji and mention it in the title too.
I think the fact it fixes the permissions should take the precedence over the docs addition.
Thanks!

2024-04-19 17:41 UTC, muraee commented
@typeid thanks for the suggestions, applied :)

2024-04-19 17:41 UTC, muraee commented
@damdo makes sense, I updated the title.

2024-04-19 18:08 UTC, nrb commented on controlplane/rosa/api/v1beta2/external_auth_types.go
> +type LocalObjectReference struct {
Why redefine this? To make it required?

2024-04-19 18:10 UTC, muraee commented on controlplane/rosa/api/v1beta2/external_auth_types.go
> +type LocalObjectReference struct {
right

2024-04-22 08:49 UTC, damdo reviewed
/lgtm
/assign @richardcase @dlipovetsky @Ankitasw

2024-04-23 14:47 UTC, damdo commented
/cherry-pick release-2.2

2024-04-23 14:47 UTC, damdo commented
/cherry-pick release-2.4

2024-04-23 14:59 UTC, nrb commented
@damdo I don't think #4915 was backported to 2.4 - do you think it should be?

2024-04-23 15:15 UTC, damdo commented
Good catch @nrb 
This will then go into v2.5.0 only.
I'll close the cherry-pick PR when it auto-opens

2024-04-23 17:15 UTC, vincepri approved these changes

2024-04-23 17:23 UTC, damdo commented
/tide refresh

2024-04-23 17:31 UTC, damdo commented
/ok-to-test

2024-04-23 18:03 UTC, merged