✨ Add non root volumes to AWSMachinePool
kubernetes-sigs/cluster-api-provider-aws pull request #4954
Opened 2024-04-25 03:55 UTC by mnitchev

**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

Adding non root volumes is already possible for the control-plane by [specifying them in the AWSMachineTemplate](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/63c66352579ef08bd365abd529e1924cde6f0d26/api/v1beta2/awsmachine_types.go#L143), but only the RootVolume can be specified for AWSMachinePools. This PR adds this feature for the machine pools as well.

**Special notes for your reviewer**:

**Checklist**:

- [x] squashed commits
- [ ] includes documentation
- [x] includes [emojis](https://github.com/kubernetes-sigs/kubebuilder-release-tools?tab=readme-ov-file#kubebuilder-project-versioning)
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
Add NonRootVolumes to AWSMachinePool launch template. 
```

2024-04-25 15:23 UTC, cnmcavoy requested changes

2024-04-25 15:23 UTC, cnmcavoy commented on pkg/cloud/services/ec2/launchtemplate.go
> +			return nil, errors.Errorf("non root volume should have device name specified")
Validation should be moved to the `awsmachinepool_webhook.go`. There's already logic in other webhooks to validate volumes, you should be able to re-use.

For example: https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/2468/files#diff-d85ef380a29a05566d8f529b89c7746d5ce4b257400061fe52be4a9ef0647668R69-R95

2024-04-30 14:48 UTC, cnmcavoy approved these changes
/lgtm

2024-06-24 11:49 UTC, mnitchev commented
@Ankitasw can you review please?

2024-08-21 12:21 UTC, AndiDog commented
/lgtm
/test pull-cluster-api-provider-aws-e2e

Ready for approval if the E2E test runs fine.

2024-08-23 09:52 UTC, AndiDog commented
/retest

2024-09-03 06:22 UTC, AndiDog commented
/approve

2024-09-03 06:57 UTC, merged