Ensure Volumes and Network Interfaces are also tagged when created as part of instance creation
kubernetes-sigs/cluster-api-provider-aws pull request #5057
Opened 2024-07-15 19:23 UTC by fahlmant

**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

ENIs and EBS Volumes that are created as part of instance creation are not being tagged with the tags that are applied to the instance. Since these resources are created as part of the AWS API call to create the instance itself, it follows that the same tags would be applied at creation time. AWS differentiates between CreateTags as a standalone API call vs CreateTags as part of a call to the RunInstances API call, and there are different required permissions for both. This change allows restrictions against standalone CreateTags calls against existing resources, while still allowing the creation of tags at on the resource.

**Special notes for your reviewer**:

**Checklist**:

- [x ] squashed commits
- [ ] includes documentation
- [ ] includes [emojis](https://github.com/kubernetes-sigs/kubebuilder-release-tools?tab=readme-ov-file#kubebuilder-project-versioning)
- [ ] adds unit tests
- [ ] adds or updates e2e tests

**Release note**:

```release-note
- EBS Volumes and ENIs are now tagged when created as part of EC2 Instance Creation. 
```

2024-07-16 00:17 UTC, fahlmant commented
/ok-to-test

2024-07-16 06:25 UTC, fiunchinho requested changes
Please, update the tests so that the new behavior is also tested.

2024-07-16 17:33 UTC, fahlmant commented
@fiunchinho tests added

2024-07-16 19:26 UTC, fahlmant commented
/retest

2024-07-16 20:30 UTC, nrb commented
/ok-to-test

2024-07-17 06:53 UTC, fiunchinho approved these changes
lgtm

2024-07-17 09:36 UTC, richardcase commented
/test ?

2024-07-17 09:37 UTC, richardcase commented
/test pull-cluster-api-provider-aws-e2e
/test pull-cluster-api-provider-aws-e2e-eks

2024-07-17 10:33 UTC, fahlmant commented
/test pull-cluster-api-provider-aws-e2e-eks

2024-07-17 14:28 UTC, fahlmant commented
/test pull-cluster-api-provider-aws-e2e-eks

2024-07-17 15:35 UTC, fahlmant commented
@richardcase The EKS test seems to be failing due to the CF stack not creating the expected IAM roles. Any guidance on what's going wrong?

2024-07-17 17:48 UTC, fahlmant commented
/test pull-cluster-api-provider-aws-e2e-eks

2024-07-18 10:32 UTC, richardcase commented
@fahlmant - i see it passing now. Sometimes we have flakes. If it persistently fails then it would be an issue with a specific test node and we'd need to look into that.

2024-07-18 10:33 UTC, richardcase commented
Considering @fiunchinho previously did an lgtm:

/lgtm
/approve

2024-07-18 10:36 UTC, merged